<?php

/** 
 * Affichage de la partie admin : liste des articles avec un bouton "modifier" pour chacun. 
 * Et un formulaire pour ajouter un article. 
 */

?>

<h2>Gestion des articles</h2>

<!-- Bouton Ajouter un article -->
<div class="admin-add-article">
    <a class="btn-add" href="<?= $this->url('/admin/formArticle') ?>">
        <i class="fa-solid fa-plus"></i> Ajouter un article</a>
</div>
<table class="article-table">
    <thead>
        <tr>
            <th><a href="<?= $this->url('/admin?sort=title&dir=' . $this->toggleSort('title')) ?>">Titre</a></th>
            <th><a href="<?= $this->url('/admin?sort=views&dir=' . $this->toggleSort('views')) ?>">Nombre de vues</a></th>
            <th><a href="<?= $this->url('/admin?sort=comments&dir=' . $this->toggleSort('comments')) ?>">Total de commentaires</a></th>
            <th><a href="<?= $this->url('/admin?sort=date_creation&dir=' . $this->toggleSort('date_creation')) ?>">Date de création</a></th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($articles as $index => $article): ?>
            <tr class="<?= $index % 2 === 0 ? 'even' : 'odd' ?>">
                <td><?= $this->clean($article['title']) ?></td>
                <td><?= $article['views'] ?></td>
                <td><?= $article['comments'] ?></td>
                <td><?= $this->formatDate($article['date_creation']) ?></td>
                <td>
                    <form class="form-actions" method="POST" action="<?= $this->url('/admin/delete/:id', ['id' => $article['id']]) ?>" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet article ?');">
                        <a class="btn-action btn-view tooltip" data-tooltip="Voir l'article" href="<?= $this->url('/articles/show/:id', ['id' => $article['id']]) ?>">
                            <i class="fa-regular fa-eye"></i>
                        </a>
                        <a class="btn-action btn-edit tooltip" data-tooltip="Modifier l'article" href="<?= $this->url('/admin/formArticle/:id', ['id' => $article['id']]) ?>">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <button type="submit" class="btn-action btn-delete tooltip" data-tooltip="Supprimer l'article">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>