<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Projet MVC OpenClassrooms">
    <link rel="stylesheet" href="../assets/style/app.css">

    <title><?= $title ?? 'Bienvenue' ?></title>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar__logo">
            <h1>Mon Super Site MVC</h1>
        </div>
        <ul class="navbar__menu">
            <li class="navbar__item"><a href="/" class="navbar__link">Accueil</a></li>
            <li class="navbar__item"><a href="/shop" class="navbar__link">Shop</a></li>
            <li class="navbar__item"><a href="/gallery" class="navbar__link">Galerie</a></li>
            <li class="navbar__item"><a href="/contact" class="navbar__link">Contact</a></li>
        </ul>
    </nav>

    <main class="main-content">
        <?php include $template; ?>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <p>&copy; <?= date('Y') ?> Mon Super Site MVC. Tous droits réservés.</p>
    </footer>
</body>

</html>