<?php

/**
 * Template principal de l'application
 */

use App\Services\ToolBox; ?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Projet MVC OpenClassrooms">
    <!-- Bootstrap 4 CDN -->
    <title>Blog | <?= isset($title) ?  ToolBox::clean($title, false) : 'Bienvenue' ?></title>
    <link rel="stylesheet" href="<?= ToolBox::url('../assets/CSS/style.css') ?>">
</head>

<body>
    <header>
        <nav>
            <a href="<?= ToolBox::url('/articles') ?>">Articles</a>
            <a href="<?= ToolBox::url('/aPropos') ?>">À propos</a>
            <!-- Si on est connecté, on affiche le bouton de déconnexion, sinon, on affiche le bouton de connexion : -->
            <?php if (isset($_SESSION['user'])): ?>
                <a href="<?= ToolBox::url('/disconnectUser') ?>">Déconnexion</a>
            <?php endif ?>
        </nav>
        <h1>Emilie Forteroche</h1>

    </header>

    <?php ToolBox::renderFlash(); ?>

    <main class="main-content">
        <?php include $template; ?>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <p>&copy; <?= date('Y') ?> Mon Super Site MVC. Tous droits réservés.</p>
    </footer>

    <!-- Bootstrap JS, jQuery, Popper.js -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->

</body>

</html>