<?php

/**
 * Template principal de l'application
 */

?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Projet MVC OpenClassrooms">
    <title>Blog | <?= isset($title) ?  $this->clean($title, false) : 'Bienvenue' ?></title>
    <link rel="stylesheet" href="<?= $this->url('../assets/CSS/style.css') ?>">
</head>

<body>
    <header>
        <nav>
            <a href="<?= $this->url('/articles') ?>">Articles</a>
            <a href="<?= $this->url('/aPropos') ?>">À propos</a>
            <!-- Si on est connecté, on affiche le bouton de déconnexion, sinon, on affiche le bouton de connexion : -->
            <?php if (isset($_SESSION['user'])): ?>
                <a href="<?= $this->url('/admin/disconnect') ?>">Déconnexion</a>
            <?php else: ?>
                <a href="<?= $this->url('/admin/connectionForm') ?>">Connexion</a>
            <?php endif ?>
        </nav>
        <h1>Emilie Forteroche</h1>

    </header>

    <?php $this->renderFlash(); ?>

    <main class="main-content">
        <?php include $template; ?>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <p>&copy; <?= date('Y') ?> Mon Super Site MVC. Tous droits réservés.</p>
    </footer>

</body>

</html>