<?php

/**
 * Fichier contenant la vue de des erreurs systeme
 */

?>

<div class="error-container">
    <div class="error-code"><?= $this->clean($statusCode); ?></div>
    <div class="error-message"><?= $this->clean($message); ?>&#9785;</div>
    <?php if (!empty($description)): ?>
        <div class="error-description"><?= $this->clean($description); ?></div>
    <?php endif; ?>
    <p><a class="error-link" href="<?= $this->url('/articles'); ?>">Retour à l'accueil</a></p>
    <pre>
        <?php print_r($trace); ?>
    </pre>
</div>