<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Erreur <?= clean($statusCode); ?></title>
    <link rel="stylesheet" href="../assets/style/app.css">
</head>

<body>
    <div class="error-container">
        <div class="error-code"><?= clean($statusCode); ?></div>
        <div class="error-message"><?= clean($message); ?></div>
        <?php if (!empty($description)): ?>
            <div class="error-description"><?= clean($description); ?></div>
        <?php endif; ?>
        <!-- Quelle alternative ici  pour afficher le chemin del'index.php ? -->
        <p><a href="<?= clean($baseUrl); ?>">Retour à l'accueil</a></p>
    </div>
</body>

</html>