<?php

/** 
 * Affichage de Liste des articles. 
 */
?>

<div class="articleList">
    <?php foreach ($articles as $article): ?>
        <article class="article">
            <h2><?= $this->clean($article['title']) ?></h2>
            <span class="quotation">«</span>
            <p><?= $this->clean($this->truncate($article['content'], 50)) ?></p>

            <div class="footer">
                <span class="info"> <?= $this->clean($this->formatDate($article['date_creation'])) ?></span>
                <a class="info" href="<?= $this->url('/articles/show/:id', ['id' => $article['id']]) ?>">Lire +</a>
            </div>
        </article>
    <?php endforeach; ?>
</div>