<?php

/**
 * Ce template affiche un article et ses commentaires.
 * Il affiche également un formulaire pour ajouter un commentaire. -->
 */

use App\Services\ToolBox; ?>
<div class="container-over-links">
    <a href="<?= ToolBox::url('/articles') ?>" class="linkBack link-left">&#9756; Retour aux articles</a>

    <div class="link-group">
        <a href="<?= ToolBox::url('/articles/edit/' . $article['id']) ?>" class="linkBack">&#9998; Éditer l'article</a>
        <a href="<?= ToolBox::url('/articles/delete/' . $article['id']) ?>" class="linkBack link-delete" onclick="return confirm('Confirmer la suppression ?')">&#10060; Supprimer</a>
    </div>
</div>

<article class="mainArticle">
    <h2> <?= ToolBox::clean($title ?? 'Détails de l\'article') ?> </h2>
    <span class="quotation">«</span>
    <p><?= ToolBox::clean($article['content']) ?></p>

    <div class="footer">
        <span class="info"> Publié le <?= ToolBox::formatDate($article['date_creation']) ?></span>
        <?php if ($article['date_update'] != null): ?>
            <span class="info"> Modifié le <?= ToolBox::formatDate($article['date_update']) ?></span>
        <?php endif ?>
    </div>
</article>

<div class="comments">
    <h2 class="commentsTitle">Vos Commentaires</h2>
    <?php if (empty($comments)): ?>
        <p class="info">Aucun commentaire pour cet article.</p>
    <?php else: ?>
        <ul>
            <?php foreach ($comments as $comment): ?>
                <li>
                    <div class="smiley">☻</div>
                    <div class="detailComment">
                        <h3 class="info">
                            Le <?= ToolBox::formatDate($article['date_creation'], 'long'); ?>,
                            <?= ToolBox::clean($comment['pseudo'], false) ?> a écrit :
                        </h3>
                        <p class="content"><?= ToolBox::clean($comment['content']) ?></p>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>

    <form action="<?= ToolBox::url('/addComment') ?>" method="post" class="foldedCorner">
        <h2>Commenter</h2>

        <div class="formComment formGrid">
            <label for="pseudo">Pseudonyme</label>
            <input type="text" name="pseudo" id="pseudo" required>

            <label for="content">Commentaire</label>
            <textarea name="content" id="content" required></textarea>

            <input type="hidden" name="action" value="addComment">
            <input type="hidden" name="idArticle" value="<?= $article['id'] ?>">

            <button class="submit">Ajouter un commentaire</button>
        </div>
    </form>
</div>