<?php

use App\Services\ToolBox; ?>

<?php if (ToolBox::hasFlash(ToolBox::ERROR)) : ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul class="mb-0">
            <?php foreach (ToolBox::getFlash(ToolBox::ERROR) as $message) : ?>
                <li><?= ToolBox::clean($message) ?></li>
            <?php endforeach; ?>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>