<?php

use App\Services\FlashMessage; ?>

<?php if (FlashMessage::has(FlashMessage::SUCCESS)) : ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <ul class="mb-0">
            <?php foreach (FlashMessage::get(FlashMessage::SUCCESS) as $message) : ?>
                <li><?= htmlspecialchars($message) ?></li>
            <?php endforeach; ?>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>