# Rôle : Déclare toutes les routes disponibles dans l'application.
# Fonctionnement :
# Liste les chemins (URI) associés à des méthodes HTTP (GET, POST, etc.).
# Associe chaque route à une "action" dans un contrôleur (ex. : Mini\Controller\IndexAction).

routes:
  "/":
    method: GET
    callable: Mini\Controller\HomeController

  # Route Authentication
  # Affichage formulaire d'inscription
  "/auth/registrationForm":
    method: GET
    callable: Mini\Controller\AuthController::displayRegistrationForm
  # Inscription
  "/auth/registration":
    method: POST
    callable: Mini\Controller\AuthController::register
  # Formulaire de connexion
  "/auth/connectionForm":
    method: GET
    callable: Mini\Controller\AuthController::displayConnectionForm
  # Connexion
  "/auth/connection":
    method: POST
    callable: Mini\Controller\AuthController::connect
  # Deconnexion
  "/auth/disconnect":
    method: GET
    callable: Mini\Controller\AuthController::disconnect
